- name: start a MariaDB container
  docker:
    image: gitinsky/mariadb:0.1.0
    state: started
    read_only: yes
    hostname: "{{ ansible_hostname }}-mariadb-{{ ext_mariadb_port }}"
    ports:
      - "{{ ext_mariadb_port }}:3306"
    volumes:
      - "{{ ext_mariadb_data_volume }}:/var/lib/mysql"
      - "{{ ext_mariadb_config_volume }}:/etc/mysql"
    name: "mariadb-{{ ext_mariadb_port }}"
    restart_policy: always
    restart_policy_retry: 10000000
